# Generated by Django 3.1.1 on 2021-02-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('vendor_id', models.IntegerField()),
                ('cluster_id', models.IntegerField()),
                ('cluster_label', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('category_label', models.CharField(max_length=255)),
                ('new_cluster', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('home_page', models.CharField(max_length=255)),
            ],
        ),
    ]
